version: 1

disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s %(levelname)s [%(name)s] %(message)s'

handlers:
  'null':
    level: DEBUG
    class: logging.NullHandler
  console:
    level: DEBUG
    formatter: default
    class: logging.StreamHandler

loggers:
  '':
    handlers:
      - console
    level: INFO
    propagate: false
  requests.packages.urllib3.connectionpool:
    handlers:
      - console
    level: WARNING
  elasticsearch:
    handlers:
      - console
    level: WARNING
